name: daily-update
'on':
  schedule:
    - cron: '11 11 * * *'
  workflow_dispatch:
jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: setup python
        uses: actions/setup-python@v4.2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run daily update
        run:  |
          cd scripts
          python update_daily.py
      - name: Save changes
        run:  |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Run daily update"
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy download folder to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: charts_download # The folder the action should deploy.
